### ISSUE TITLE
Run error in stereo camera (Bumblebee2)

### ISSUE THREAD

**Issue by symao** [srv/fovis#13]
Hi all,

I'm using Bumblebee2 to run fovis in ros for stereo VO, the fovis_note always output failed status which is INSUFFICIENT INLIERS.

Here is my test process:
roslaunch camera1394stereo stereo_camera_full.launch
rosrun fovis_ros fovis_stereo_odometer stereo:=stereo_camera image:=image_raw

Do I run it in a right way?
I note that fovis_ros tells me a warn that i should use image_rect. Is that the reason?
What's the difference between image_raw and image_rect? 

Thanks.

**Comment by miquelmassot** [comment]
In order to find corresponding features in the two images (left and right) the camera has to be previously calibrated.
- _image_raw_: means the image is not calibrated, in the raw data format of the camera (bayer, mono, color...) :-1: 
- _image_rect_: means that the image is calibrated (correspondences between left and right images can be easily found) and with the datatype fovis expects. :+1: 

First [calibrate your camera](http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration), and then use image_rect(_color).

**Comment by symao** [comment]
@miquelmassot 
Thank you. I already calibrate the camera. Is there any ros node that transfer image_raw to image_rect given calibrate result?

**Comment by miquelmassot** [comment]
See http://wiki.ros.org/stereo_image_proc
